#ifndef _VERSION_H
#define _VERSION_H

#define TESTRUNNER_VERSION_MAJOR "1"
#define TESTRUNNER_VERSION_MINOR "0"
#define TESTRUNNER_VERSION_PATCH "0"
#define TESTRUNNER_VERSION TESTRUNNER_VERSION_MAJOR "." TESTRUNNER_VERSION_MINOR "." TESTRUNNER_VERSION_PATCH

#endif // _VERSION_H
